open_cli_sample_version: 1.0
name: cloud-list
version: onap-dublin
samples:
  sample1:
    name: cloud-list
    input: 
    moco: cloud-list-schema-dublin-moco.json
    output: |
      +--------------+------------+------------------+
      |cloud         |region      |resource-version  |
      +--------------+------------+------------------+
      |huawei-cloud  |bangalore   |1538643783460     |
      +--------------+------------+------------------+
